project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: George Wood
  google-analytics: "UA-XXXXXXXX"
  page-navigation: true
  search: false
  navbar:
    background: primary
    left:
      - text: "About"
        file: about.qmd
      - text: "Software"
        file: software.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme:
      light: [cosmo, scss/light.scss] # flatly, pulse, zephyr
    # css: custom.css
    toc: false

editor: source
