project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "George Wood"
  site-url: https://george-wood.github.io
  repo-url: https://github.com/george-wood/george-wood.github.io
  repo-actions: []
  
  page-footer: 
    left: "&copy; Copyright 2023, George Wood"
    right: 
      - icon: github
        href: https://github.com/george-wood/george-wood.github.io
      - icon: twitter
        href: https://twitter.com/_georgewood

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Research"
        href: research/research.qmd
      
      - text: "Teaching"
        href: teaching/teaching.qmd
        
      - text: "R Packages"
        href: rpkg/rpkg.qmd
        
      - text: "About"
        href: about.qmd
           
      #- text: "Talks"
      #  href: talks/talks.qmd

      #- text: "Notes"
      #  href: blog/blog.qmd

      #- text: "About"
      #  menu: 
          #- text: "About me"
          #  href: about_me.qmd
          #- text: "CV"
          #  href: misc/info/cv_george_wood.pdf

format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: "Inter"
    fontsize: 1.1em


