---
title: ""
pagetitle: "About - George Wood"
---

::: {.column-screen-inset}

::: {.grid}

::: {.g-col-12 .g-col-md-12 .g-col-lg-10 .g-col-xl-9 .g-col-xxl-6}

# I'm a data scientist and R developer with a background in computational social science. My work focuses on causal inference in observational settings, with application to criminal justice and gun violence. I have a longstanding interest in sports analytics and developing data science tools.

\ 

### Education

::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
**Nuffield College, University of Oxford**  
PhD in Sociology

- Research Areas: Computational Social Science, Statistical Inference on Networks, Gun Violence
- Funded by Economic and Social Research Council
:::
::: {.flex-shrink-0}
2017
:::
:::


::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
**St Cross College, University of Oxford**  
MSc in Sociology
:::
::: {.flex-shrink-0}
2012
:::
:::


::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
**University of Sheffield**  
BA in Sociology with First-Class Honours
:::
::: {.flex-shrink-0}
2011
:::
:::


### Experience

::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
**New York University**  
Moore-Sloan Faculty Fellow, Center for Data Science
:::
::: {.flex-shrink-0}
2020--present
:::
:::


::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
**Northwestern University**  
Postdoctoral Fellow, Institute for Policy Research
:::
::: {.flex-shrink-0}
2019--2020
:::
:::


::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
**Yale University**  
Postdoctoral Associate, Institution for Social and Policy Studies
:::
::: {.flex-shrink-0}
2017--2019
:::
:::

### Teaching

**New York University**

::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
`DS-GA 1017` and `DS-UA 202` Responsible Data Science

- Technical course that covers data quality, algorithmic fairness, transparency of data and algorithms, ethics, privacy, and data protection.
- Find out more about the course [here](https://dataresponsibly.github.io/rds/).
:::
::: {.flex-shrink-0}
2021, 2022
:::
:::


::: {.d-flex .justify-content-between}
::: {.flex-grow-1}
`DS-UA 111` Data Science for Everyone 

- Flagship course at the Center for Data Science.
- Designed for students without prior statistics or programming experience.
:::
::: {.flex-shrink-0}
2021, 2022
:::
:::

### Programming

:::: {.columns}

::: {.column width="30%"}
Languages 

Tools

Frameworks

Practices
:::

::: {.column width="70%"}
R, Python, SQL

Git, GitHub Actions, Docker

Shiny, Quarto, BigQuery

Automated workflows, CI/CD, version control, unit testing, packaging, parallel programming
:::

::::


:::
:::
:::
