---
title: ""
pagetitle: "Publications - George Wood"
---

::: column-screen-inset
::: grid
::: {.g-col-12 .g-col-sm-10 .g-col-md-9 .g-col-lg-6 .g-col-xl-6 .g-col-xxl-6}
::: {.d-flex .flex-column}
## Publications

-   [Revised findings: Procedural justice training reduces police use of force and complaints against officers](https://osf.io/preprints/socarxiv/xf32m/)<br>
    G Wood, TR Tyler, AV Papachristos, J Roth, PHC Sant'Anna<br>
    *SocArXiv*, 2021

-   [Procedural justice training reduces police use of force and complaints against officers](https://www.pnas.org/doi/full/10.1073/pnas.1920671117)<br>
    G Wood, TR Tyler, AV Papachristos<br>
    *Proceedings of the National Academy of Sciences*, 2020

-   [Building community resilience to prevent and mitigate community impact of gun violence: conceptual framework and intervention design](https://bmjopen.bmj.com/content/10/10/e040277)<br>
    EA Wang, C Riley, G Wood, A Greene, N Horton, M Williams, P Violano, RM Brase, L Brinkley-Rubinstein, AV Papachristos, B Roy<br>
    *BMJ Open*, 2020

-   [The network structure of police misconduct](https://journals.sagepub.com/doi/full/10.1177/2378023119879798)<br>
    G Wood, D Roithmayr, AV Papachristos<br>
    *Socius*, 2019

-   [Reducing gunshot victimization in high-risk social networks through direct and spillover effects](https://www.nature.com/articles/s41562-019-0688-1)<br>
    G Wood, AV Papachristos<br>
    *Nature Human Behaviour*, 2019

-   [The structure and vulnerability of a drug trafficking collaboration network](https://www.sciencedirect.com/science/article/abs/pii/S0378873316302702)<br>
    G Wood<br>
    *Social Networks*, 2017

:::
:::
:::
:::
